var GameConstants = {
  RECEIVE_GAME: "RECEIVE_GAME",
  RECEIVE_GAMES: "RECEIVE_GAMES",
  RECEIVE_MOVE: "RECEIVE_MOVE",
  MOVE_ERROR: 'MOVE_ERROR',
  MOVE_SELECTED: 'MOVE_SELECTED',
  MOVE_DESELECTED: 'MOVE_DESELECTED',
  ADD_GAME: 'ADD_GAME'
};

module.exports = GameConstants;
