var GameConstants = {
  RECEIVE_GAME: "RECEIVE_GAME",
  RECEIVE_GAMES: "RECEIVE_GAMES",
  RECEIVE_MOVE: "RECEIVE_MOVE",
  MOVE_ERROR: 'MOVE_ERROR',
  MOVE_SELECTED: 'MOVE_SELECTED'
};

module.exports = GameConstants;
